### ISSUE TITLE
fuck you

### ISSUE THREAD

**Issue by FrozenHyper** [Assassin-1234/mee6#4]
asshole, you think you're so funny.
anyone can look at the source code and see what you're doing.

**Comment by Assassin-1234** [comment]
ofc, take a look at https://github.com/Assassin-1234/mee6/blob/main/src/index.js#L2 and see who the asshole here is ^^

- as you can see, it doesnt ping since mentions are disabled via client options.

- This repository is meant for guys like you anyway who copy codes without even checking what it is and looking at your profile I think you found it for a reason!! 😱

- 3 repositories on your profile out of which one is fork and the other 2 are markdown, same for your organization, which only has one html basic to-do list and the other 2 are markdown

next time think about yourself before opening an issue :)

**Comment by LegItMate** [comment]
If anyone is fucking dumb enough to run a random code without even checking it and think it will work like a charm, then they need to get some help. Attacking an author for creating a funny code like a kid when the code isn't even doing severe damage? Get a better sense of humour dumbass

Seeing your profile you look like that guy who's dumb enough to fall for that 🙃

Get better asshole ☺️

**Comment by Assassin-1234** [comment]
been quiet here 👀what happened @HyperfireRS
